{{- $values := .Values.aggregator -}}
{{- $service := "aggregator" -}}
{{- $kafka := .Values.kafkaSettings -}}
{{- $kafkaName := (print (include "helm.fullname" .) "-kafka") }}
{{- $influxDb := .Values.influxdb2 -}}
{{- $influxDbName := (print (include "helm.fullname" .) "-influxdb2") }}
{{- $timescaledb := .Values.timescaledb -}}
{{- $timescaledbName := (print (include "helm.fullname" .) "-timescaledb") }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helm.fullname" . }}-{{ $service }}-secrets
data:
  DISABLE: {{ $values.disable | toString | b64enc | quote }}
  HOST: {{ "0.0.0.0" | b64enc | quote }}
  PORT: {{ $values.service.port | toString | b64enc | quote }}
  INFLUXDB_HOST: {{ $influxDbName | b64enc | quote }}
  INFLUXDB_TOKEN: {{ $influxDb.adminUser.token | b64enc | quote }}
  INFLUXDB_ORG: {{ $influxDb.adminUser.organization | b64enc | quote }}
  INFLUXDB_BUCKET: {{ $influxDb.adminUser.bucket | b64enc | quote }}
  POSTGRES_HOST: {{ $timescaledbName | toString | b64enc | quote }}
  POSTGRES_PORT: {{ $timescaledb.port | toString | b64enc | quote }}
  POSTGRES_USER: {{ $timescaledb.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $timescaledb.pass | b64enc | quote }}
  POSTGRES_USE_SSL: {{- if $timescaledb.useSsl }} {{ "1" | b64enc }} {{- else }} {{ "0" | b64enc }} {{- end }}
  POSTGRES_DB: {{ $timescaledb.database | b64enc | quote }}
