// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	Sku         string  `json:"sku"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description *string `json:"description"`
}

func (Product) IsEntity() {}
