{{- $values := .Values.eventApi -}}
{{- $service := "event-api" -}}
{{- $kafka := .Values.kafkaSettings -}}
{{- $kafkaName := (print (include "helm.fullname" .) "-kafka") }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helm.fullname" . }}-{{ $service }}-secrets
data:
  HOST: {{ "0.0.0.0" | b64enc | quote }}
  PORT: {{ $values.service.port | toString | b64enc | quote }}
  KAFKA_HOST: {{ $kafkaName | b64enc | quote }}
  KAFKA_PORT: {{ $kafka.port | toString | b64enc | quote }}
  KAFKA_TOPIC:  {{ $kafka.topic | b64enc | quote }}
