apiVersion: v2
name: streamproc
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kafka
    repository: https://charts.bitnami.com/bitnami/kafka
    version: "17.2.5"
