{{- $values := .Values.eventProducer -}}
{{- $service := "event-producer" -}}
{{- $eventApiName := (print (include "helm.fullname" .) "-event-api") }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helm.fullname" . }}-{{ $service }}-secrets
data:
  DISABLE: {{ $values.disable | toString | b64enc | quote }}
  API_HOST: {{ $eventApiName | b64enc | quote }}
  API_PORT: {{ .Values.eventApi.service.port | toString | b64enc | quote }}
