CREATE USER 'web';
GRANT SELECT, INSERT, UPDATE, DELETE ON snippetbox.* TO 'web';
ALTER USER 'web' IDENTIFIED BY 'pass';

CREATE USER 'test_web';
GRANT CREATE, DROP, ALTER, INDEX, SELECT, INSERT, UPDATE, DELETE ON test_snippetbox.* TO 'test_web';
ALTER USER 'test_web' IDENTIFIED BY 'pass';
