{{- $values := .Values.timescaledb -}}
{{- $service := "timescaledb" -}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helm.fullname" . }}-{{ $service }}-secrets
data:
  POSTGRES_DB: {{ $values.database | b64enc | quote }}
  POSTGRES_USER: {{ $values.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $values.pass | b64enc | quote }}
  POSTGRES_PORT: {{ $values.port | toString | b64enc | quote }}
  POSTGRES_USE_SSL: {{- if $values.useSsl }} {{ "1" | b64enc }} {{- else }} {{ "0" | b64enc }} {{- end }}
