{{- $values := .Values.consumerLow -}}
{{- $service := "consumer-low" -}}
{{- $kafka := .Values.kafkaSettings -}}
{{- $kafkaName := (print (include "helm.fullname" .) "-kafka") }}
{{- $influxDb := .Values.influxdb2 -}}
{{- $influxDbName := (print (include "helm.fullname" .) "-influxdb2") }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helm.fullname" . }}-{{ $service }}-secrets
data:
  DISABLE: {{ $values.disable | toString | b64enc | quote }}
  HOST: {{ "0.0.0.0" | b64enc | quote }}
  PORT: {{ $values.service.port | toString | b64enc | quote }}
  KAFKA_HOST: {{ $kafkaName | b64enc | quote }}
  KAFKA_PORT: {{ $kafka.port | toString | b64enc | quote }}
  KAFKA_TOPIC:  {{ $kafka.topic | b64enc | quote }}
  INFLUXDB_HOST: {{ $influxDbName | b64enc | quote }}
  INFLUXDB_TOKEN: {{ $influxDb.adminUser.token | b64enc | quote }}
  INFLUXDB_ORG: {{ $influxDb.adminUser.organization | b64enc | quote }}
  INFLUXDB_BUCKET: {{ $influxDb.adminUser.bucket | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helm.fullname" . }}-{{ $service }}-init-secrets
data:
  KAFKA_HOST: {{ $kafkaName | b64enc | quote }}
  KAFKA_PORT: {{ $kafka.port | toString | b64enc | quote }}
  INFLUXDB_HOST: {{ $influxDbName | b64enc | quote }}
  INFLUXDB_USER: {{ $influxDb.adminUser.user | b64enc | quote }}
  INFLUXDB_PASSWORD: {{ $influxDb.adminUser.password | b64enc | quote }}
