// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	Title       *string    `json:"title"`
	Description *string    `json:"description"`
	Products    []*Product `json:"products"`
}

type Product struct {
	Sku string `json:"sku"`
}

func (Product) IsEntity() {}
