{{- $values := .Values.consumerHigh -}}
{{- $service := "consumer-high" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-{{ $service }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $service }}
spec:
  {{- if not $values.autoscaling.enabled }}
  replicas: {{ $values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $service }}
  template:
    metadata:
      annotations:
        {{- with $values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        timestamp: {{ now | quote }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $service }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: tsdb-init
          image: postgres:14.3
          command: [ "sh", "-c", "until psql -c ''; do echo waiting for tsdb; sleep 2; done"]
          envFrom:
            - secretRef:
                name: {{ include "helm.fullname" . }}-{{ $service }}-init-secrets
        - name: kafka-init
          image: edenhill/kcat:1.7.1
          command: ["sh", "-c", "until kcat -b $KAFKA_HOST:$KAFKA_PORT -L; do echo waiting for kafka; sleep 2; done"]
          envFrom:
            - secretRef:
                name: {{ include "helm.fullname" . }}-{{ $service }}-init-secrets
      containers:
        - name: {{ $service }}
          securityContext:
            {{- toYaml $values.securityContext | nindent 12 }}
          image: "{{ $values.image.repository }}:{{ $values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "helm.fullname" . }}-{{ $service }}-secrets
          ports:
            - name: http
              containerPort: {{ $values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $values.resources | nindent 12 }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
